### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import pandas as pd

# File to Load (Remember to Change These)
school_data_to_load = "Resources/schools_complete.csv"
student_data_to_load = "Resources/students_complete.csv"

# Read School and Student Data File and store into Pandas DataFrames
school_data = pd.read_csv(school_data_to_load)
student_data = pd.read_csv(student_data_to_load)

# Combine the data into a single dataset.  
school_data_complete = pd.merge(student_data, school_data, how="left", on=["school_name", "school_name"])

school_data_complete.head(11)

,Student ID,student_name,gender,grade,school_name,reading_score,math_score,School ID,type,size,budget
0,0,Paul Bradley,M,9th,Huang High School,66,79,0,District,2917,1910635
1,1,Victor Smith,M,12th,Huang High School,94,61,0,District,2917,1910635
2,2,Kevin Rodriguez,M,12th,Huang High School,90,60,0,District,2917,1910635
3,3,Dr. Richard Scott,M,12th,Huang High School,67,58,0,District,2917,1910635
4,4,Bonnie Ray,F,9th,Huang High School,97,84,0,District,2917,1910635
5,5,Bryan Miranda,M,9th,Huang High School,94,94,0,District,2917,1910635
6,6,Sheena Carter,F,11th,Huang High School,82,80,0,District,2917,1910635
7,7,Nicole Baker,F,12th,Huang High School,96,69,0,District,2917,1910635
8,8,Michael Roth,M,10th,Huang High School,95,87,0,District,2917,1910635
9,9,Matthew Greene,M,10th,Huang High School,96,84,0,District,2917,1910635
10,10,Andrew Alexander,M,10th,Huang High School,90,70,0,District,2917,1910635

In [2]:
#convert budget and size data type to integer 
school_data["budget"] = pd.to_numeric(school_data["budget"])
student_data["size"] = pd.to_numeric(school_data["size"])

#convert score / size / budget data type to integer 
school_data_complete["reading_score"] = pd.to_numeric(school_data_complete["reading_score"])
school_data_complete["math_score"] = pd.to_numeric(school_data_complete["math_score"])
school_data_complete["size"] = pd.to_numeric(school_data_complete["size"])
school_data_complete["budget"] = pd.to_numeric(school_data_complete["budget"])

# calculate total school
total_school = len(school_data_complete["School ID"].unique())

# calculate total school
total_student = len(school_data_complete["Student ID"].unique())

#calculate total budget
total_budget = school_data["budget"].sum()

# calculate Average Math Score
avg_math = school_data_complete["math_score"].mean()

# calculate Average Reading Score
avg_reading = school_data_complete["reading_score"].mean()

# % passing math
passing_math_percent = school_data_complete.loc[school_data_complete["math_score"]>=70]["math_score"].count()/total_student
passing_math_percent
# % passing reading
passing_reading_percent = school_data_complete.loc[school_data_complete["reading_score"]>=70]["reading_score"].count()/total_student

# overall Passing Rate
overall_passing_rate = (passing_reading_percent + passing_math_percent)/2

## District Summary

* Calculate the total number of schools

* Calculate the total number of students

* Calculate the total budget

* Calculate the average math score 

* Calculate the average reading score

* Calculate the percentage of students with a passing math score (70 or greater)

* Calculate the percentage of students with a passing reading score (70 or greater)

* Calculate the percentage of students who passed math **and** reading (% Overall Passing)

* Create a dataframe to hold the above results

* Optional: give the displayed data cleaner formatting

In [5]:
#create a new dataframe for summary
district_summary = pd.DataFrame({
    "Total Schools":[total_school],
    "Total Students":[total_student],
    "Total Budget":[total_budget],
    "Average Math Score":[avg_math],
    "Average Reading Score":[avg_reading],
    "% Passing Math":[passing_math_percent],
    "% Passing Reading":[passing_reading_percent],
    "Overall Passing Rate":[overall_passing_rate]                            
})

district_summary.head()

,Total Schools,Total Students,Total Budget,Average Math Score,Average Reading Score,% Passing Math,% Passing Reading,Overall Passing Rate
0,15,39170,24649428,78.985371,81.87784,0.749809,0.858055,0.803932

In [ ]:
#rearrange columns
district_summary = district_summary[["Total Schools",
                                 "Total Students",
                                 "Total Budget",
                                 "Average Math Score",
                                 "Average Reading Score",
                                 "% Passing Math",
                                 "% Passing Reading",
                                 "Overall Passing Rate"                            
                                    ]]

In [ ]:
#change format 
district_summary['Total Budget'] = district_summary['Total Budget'].map("${:,.2f}".format)
district_summary['Average Math Score'] = district_summary['Average Math Score'].map("{:,.2f}".format)
district_summary['Average Reading Score'] = district_summary['Average Reading Score'].map("{:,.2f}".format)
district_summary['Total Students'] = district_summary['Total Students'].map("{:,}".format)
district_summary['Overall Passing Rate'] = district_summary['Overall Passing Rate'].map("{:.1%}".format)
district_summary['% Passing Math'] = district_summary['% Passing Math'].map("{:.1%}".format)
district_summary['% Passing Reading'] = district_summary['% Passing Reading'].map("{:.1%}".format)

In [ ]:
Total_Number_of_Purchase = (purchase_data["Purchase ID"]).count()

## School Summary

* Create an overview table that summarizes key metrics about each school, including:
  * School Name
  * School Type
  * Total Students
  * Total School Budget
  * Per Student Budget
  * Average Math Score
  * Average Reading Score
  * % Passing Math
  * % Passing Reading
  * % Overall Passing (The percentage of students that passed math **and** reading.)
  
* Create a dataframe to hold the above results

In [ ]:
School Name
School Type
Total Students
Total School Budget
Per Student Budget
Average Math Score
Average Reading Score
% Passing Math
% Passing Reading
Overall Passing Rate (Average of the above two)

'''
#school name
school_name = school_data_complete.set_index('school').groupby(['school'])

#school types
sch_types = sch_df.set_index('school')['type']

#Total Students
total_stu = school_name["Student ID"].count()


#Total School Budget
total_budg = sch_df.set_index('school')['budget']

#Per Student Budget
per_stu_budget = total_budg/total_stu

#Average Math Score
avg_math_score = school_name["math_score"].mean()

#Average Reading Score
avg_reading_score = school_name["reading_score"].mean()

# % Passing Math
percent_pass_math = school_data_complete.loc[school_data_complete["math_score"] >= 70].groupby('school')['Student ID'].count()/total_stu

# % Passing reading
percent_pass_reading = school_data_complete.loc[school_data_complete["reading_score"] >= 70].groupby('school')['Student ID'].count()/total_stu

# Overall Passing Rate
overall_pass_rate = (percent_pass_math + percent_pass_reading)/2

In [ ]:
#create school summary dataframe

school_summary = pd.DataFrame({
                               "School Type" : sch_types,
                               "Total Students" : total_stu,
                               "Total School Budget" : total_budg,
                               "Per Student Budget" : per_stu_budget,
                               "Average Math Score" : avg_math_score,
                               "Average Reading Score" : avg_reading_score,
                               "% Passing Math": percent_pass_math,
                               "% Passing Reading" : percent_pass_reading,
                               "Overall Passing Rate" : overall_pass_rate
    
                            })



#rearrange the order

school_summary = school_summary [[ "School Type", 
                                   "Total Students", 
                                   "Total School Budget",
                                   "Per Student Budget",
                                   "Average Math Score",
                                   "Average Reading Score",
                                   "% Passing Math",
                                   "% Passing Reading",
                                   "Overall Passing Rate"
                                   
                                   ]]
    

    
#format the df

school_summary['Total Students'] = school_summary['Total Students'].map("{:,}".format)
school_summary['Total School Budget'] = school_summary['Total School Budget'].map("{:,}".format)
school_summary['Per Student Budget'] = school_summary['Per Student Budget'].map("{:.2f}".format)
school_summary['Average Math Score'] = school_summary['Average Math Score'].map("{:.1f}".format)
school_summary['Average Reading Score'] = school_summary['Average Reading Score'].map("{:.1f}".format)
school_summary['% Passing Math'] = school_summary['% Passing Math'].map("{:.2%}".format)
school_summary['% Passing Reading'] = school_summary['% Passing Reading'].map("{:.2%}".format)
school_summary['Overall Passing Rate'] = school_summary['Overall Passing Rate'].map("{:.2%}".format)

school_summary

## Top Performing Schools (By % Overall Passing)

* Sort and display the top five performing schools by % overall passing.

In [ ]:
# sort df by passing rate and print the top 5 rows

sorting_sch = school_summary.sort_values(['Overall Passing Rate'], ascending=[False])
sorting_sch.head(5)

## Bottom Performing Schools (By % Overall Passing)

* Sort and display the five worst-performing schools by % overall passing.

In [ ]:
# print last 5 row from sorted df, and re-sort ascending by passing rate
Bottom_schools = sorting_sch.tail(5)
Bottom_schools.sort_values(['Overall Passing Rate'], ascending=[True])

## Math Scores by Grade

* Create a table that lists the average Reading Score for students of each grade level (9th, 10th, 11th, 12th) at each school.

  * Create a pandas series for each grade. Hint: use a conditional statement.
  
  * Group each series by school
  
  * Combine the series into a dataframe
  
  * Optional: give the displayed data cleaner formatting

In [ ]:
'''
Math Scores by Grade**
Create a table that lists the average Math Score for students of each grade level (9th, 10th, 11th, 12th) at each school.
'''
#check how many grades
#merge_df['grade'].unique()

# create table to store average math score for each grade by school
math_9th = merge_df.loc[school_data_complete["grade"] == '9th'].groupby('school')['math_score'].mean()
math_10th = merge_df.loc[school_data_complete["grade"] == '10th'].groupby('school')['math_score'].mean()
math_11th = merge_df.loc[school_data_complete["grade"] == '11th'].groupby('school')['math_score'].mean()
math_12th = merge_df.loc[school_data_complete["grade"] == '12th'].groupby('school')['math_score'].mean()

#create math averge by grade dataframe

avg_math_df = pd.DataFrame({"9th": math_9th,
                            "10th": math_10th,
                            "11th": math_11th,
                            "12th": math_12th,
    
                            })

#rearragne the order
avg_math_df = avg_math_df[["9th","10th","11th","12th"]]

avg_math_df

## Reading Score by Grade

* Perform the same operations as above for reading scores

In [ ]:
# create table to store average reading score for each grade by school
reading_9th = school_data_complete.loc[school_data_complete["grade"] == '9th'].groupby('school')['reading_score'].mean()
reading_10th = school_data_complete.loc[school_data_complete["grade"] == '10th'].groupby('school')['reading_score'].mean()
reading_11th = school_data_complete.loc[school_data_complete["grade"] == '11th'].groupby('school')['reading_score'].mean()
reading_12th = school_data_complete.loc[school_data_complete["grade"] == '12th'].groupby('school')['reading_score'].mean()

#create reading averge by grade dataframe

avg_reading_df = pd.DataFrame({"9th": reading_9th,
                            "10th": reading_10th,
                            "11th": reading_11th,
                            "12th": reading_12th,
    
                            })
#rearragne the order
avg_reading_df = avg_reading_df[["9th","10th","11th","12th"]]

avg_reading_df

## Scores by School Spending

* Create a table that breaks down school performances based on average Spending Ranges (Per Student). Use 4 reasonable bins to group school spending. Include in the table each of the following:
  * Average Math Score
  * Average Reading Score
  * % Passing Math
  * % Passing Reading
  * Overall Passing Rate (Average of the above two)

In [ ]:
''
Scores by School Spending
Create a table that breaks down school performances based on average Spending Ranges (Per Student). Use 4 reasonable bins to group school spending. Include in the table each of the following:

Average Math Score
Average Reading Score
% Passing Math
% Passing Reading
Overall Passing Rate (Average of the above two)
'''
#school_summary['Per Student Budget'].min()
# output 578.0

#school_summary['Per Student Budget'].max()
# output 655.0

school_summary["Average Math Score"] = pd.to_numeric(school_summary["Average Math Score"])
school_summary["Average Reading Score"] = pd.to_numeric(school_summary["Average Reading Score"])

school_summary["Per Student Budget"] = pd.to_numeric(school_summary["Per Student Budget"])

school_summary["% Passing Math"] = school_summary["% Passing Math"].replace('%', '', regex=True).astype('float')
school_summary["% Passing Math"] = pd.to_numeric(school_summary["% Passing Math"])

school_summary["% Passing Reading"] = school_summary["% Passing Reading"].replace('%', '', regex=True).astype('float')
school_summary["% Passing Reading"] = pd.to_numeric(school_summary["% Passing Reading"])

# create the bins in which Data will be held
bins = [0, 585, 615, 645, 675]
# create group of categories
group_name = ['< $585', "$585-615", "$615-645", "$645-675"]

# putting data into categories
school_summary['Spending Ranges (Per Student)'] = pd.cut(school_summary['Per Student Budget'], bins = bins, labels = group_name)

# group the data set by spending ranges
by_spending_range = school_summary.groupby(['Spending Ranges (Per Student)'])

# calculate score and passing rate by Spending Ranges (Per Student)
mean_math_score = by_spending_range["Average Math Score"].mean()
mean_reading_score = by_spending_range["Average Reading Score"].mean()
mean_percent_math = by_spending_range["% Passing Math"].mean()
mean_percent_reading = by_spending_range["% Passing Reading"].mean()
overall_percent_pass = (mean_percent_math + mean_percent_reading)/2

#create a df to store Scores by School Spending
scores_by_school_spending = pd.DataFrame({"Average Math Score":mean_math_score,
                                          "Average Reading Score":mean_reading_score,
                                          "% Passing Math":mean_percent_math,
                                          "% Passing Reading":mean_percent_reading,
                                          "% Overall Passing Rate":overall_percent_pass
                                         })

# reformating
scores_by_school_spending['Average Math Score'] = scores_by_school_spending['Average Math Score'].map("{:,.2f}".format)
scores_by_school_spending['Average Reading Score'] = scores_by_school_spending['Average Reading Score'].map("{:,.2f}".format)
scores_by_school_spending['% Passing Math'] = scores_by_school_spending['% Passing Math'].map("{:.2f}".format)
scores_by_school_spending['% Passing Reading'] = scores_by_school_spending['% Passing Reading'].map("{:.2f}".format)
scores_by_school_spending['% Overall Passing Rate'] = scores_by_school_spending['% Overall Passing Rate'].map("{:.2f}".format)

#rearrage columns
scores_by_school_spending = scores_by_school_spending [["Average Math Score",
                            "Average Reading Score",
                            "% Passing Math",
                            "% Passing Reading",
                            "% Overall Passing Rate"]]

# print out the table
scores_by_school_spending

## Scores by School Size

* Perform the same operations as above, based on school size.

In [ ]:
 create the bins in which Data will be held
bins1 = [0, 1000, 2000, 5000]
# create group of categories
group_name1 = ['Small (<1000)', "Medium (1000-2000)", "Large (2000-5000)"]

# putting data into categories
school_summary["Total Students"] = school_summary["Total Students"].replace(',', '', regex=True).astype('float')
school_summary['Total Students'] = pd.to_numeric(school_summary['Total Students'])
school_summary['School Size'] = pd.cut(school_summary['Total Students'], bins = bins1, labels = group_name1)

# group the data set by school size
by_size = school_summary.groupby(['School Size'])

# calculate score and passing rate by school size
mean_math_score = by_size["Average Math Score"].mean()
mean_reading_score = by_size["Average Reading Score"].mean()
mean_percent_math = by_size["% Passing Math"].mean()
mean_percent_reading = by_size["% Passing Reading"].mean()
overall_percent_pass = (mean_percent_math + mean_percent_reading)/2



#create a df to store Scores by School Size
by_size_df = pd.DataFrame({"Average Math Score":mean_math_score,
                                          "Average Reading Score":mean_reading_score,
                                          "% Passing Math":mean_percent_math,
                                          "% Passing Reading":mean_percent_reading,
                                          "% Overall Passing Rate":overall_percent_pass
                                         })

# reformating
by_size_df['Average Math Score'] = by_size_df['Average Math Score'].map("{:,.2f}".format)
by_size_df['Average Reading Score'] = by_size_df['Average Reading Score'].map("{:,.2f}".format)
by_size_df['% Passing Math'] = by_size_df['% Passing Math'].map("{:.2f}".format)
by_size_df['% Passing Reading'] = by_size_df['% Passing Reading'].map("{:.2f}".format)
by_size_df['% Overall Passing Rate'] = by_size_df['% Overall Passing Rate'].map("{:.2f}".format)

#rearrage columns
by_size_df = by_size_df [["Average Math Score",
                            "Average Reading Score",
                            "% Passing Math",
                            "% Passing Reading",
                            "% Overall Passing Rate"]]

# print out the table

## Scores by School Type

* Perform the same operations as above, based on school type

In [ ]:
# group the data set by school type
by_school_type = school_summary.groupby(['School Type'])

# calculate score and passing rate by school type
mean_math_score = by_school_type["Average Math Score"].mean()
mean_reading_score = by_school_type["Average Reading Score"].mean()
mean_percent_math = by_school_type["% Passing Math"].mean()
mean_percent_reading = by_school_type["% Passing Reading"].mean()
overall_percent_pass = (mean_percent_math + mean_percent_reading)/2



#create a df to store Scores by School Type
by_shool_type_df = pd.DataFrame({"Average Math Score":mean_math_score,
                                          "Average Reading Score":mean_reading_score,
                                          "% Passing Math":mean_percent_math,
                                          "% Passing Reading":mean_percent_reading,
                                          "% Overall Passing Rate":overall_percent_pass
                                         })

# reformating
by_shool_type_df['Average Math Score'] = by_shool_type_df['Average Math Score'].map("{:,.2f}".format)
by_shool_type_df['Average Reading Score'] = by_shool_type_df['Average Reading Score'].map("{:,.2f}".format)
by_shool_type_df['% Passing Math'] = by_shool_type_df['% Passing Math'].map("{:.2f}".format)
by_shool_type_df['% Passing Reading'] = by_shool_type_df['% Passing Reading'].map("{:.2f}".format)
by_shool_type_df['% Overall Passing Rate'] = by_shool_type_df['% Overall Passing Rate'].map("{:.2f}".format)

#rearrage columns
by_shool_type_df = by_shool_type_df [["Average Math Score",
                            "Average Reading Score",
                            "% Passing Math",
                            "% Passing Reading",
                            "% Overall Passing Rate"]]

# print out the table
by_shool_type_df